version: '3'

services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8008
        volumes:
            - .:/app
        ports:
            - "8008:8008"
    redis:
        container_name: "redis"
        image: "redis:alpine"
        expose:
            - '6379'
        ports:
            - "6379:6379"