version: '3'

services:
    web:
        build: .
        image: django-rest
        command: >
             bash -c "python manage.py wait_for_db
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8008"
        volumes:
            - .:/app
        environment:
            - SECRET_KEY=devsecretkey
            - DEBUG=1
            - DB_HOST=db
            - DB_NAME=postgres
            - DB_USER=postgres
            - DB_PASS=root
        ports:
            - "8008:8008"
        # depends_on:
        #     - migration
        depends_on:
            - db

        
    # migration:
    #     build: .
    #     command: python manage.py migrate
    #     volumes:
    #         - .:/app
    #     links:
    #         - db
    #     depends_on:
    #         - db
    redis:
        container_name: "redis"
        image: "redis:alpine"
        expose:
            - '6379'
        ports:
            - "6379:6379"
    db:
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root